config/routes.rb
Rails.application.routes.draw do
  resources :murmurs do
    collection do
      post :confirm
      get :top
    end
  end
  
  root to:'murmur#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/murmur.rb
class Murmur < ApplicationRecord
  validates :content, length:{in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/murmurs_controller.rb
class MurmursController < ApplicationController
  before_action :set_murmur, only:[:show, :edit, :update, :destroy]
  
  def index
    @murmur = Murmur.all
  end
  
  def new
    @murmur = Murmur.new
  end
  
  def confirm
    @murmur = Murmur.new(murmur_params)
  end
  
  def create
    @murmur = Murmur.new(murmur_params)
    if @murmur.save
      redirect_to murmurs_path, notice:"上手につぶやけました！"
    else
      render'new'
    end
  end
  
  def edit
  end
  
  def show
  end
  
  def update
    if @murmur.update(murmur_params)
      redirect_to murmurs_path, notice:"もっと上手につぶやけました！"
    else
      render'edit'
    end
  end
  
  def destroy
    @murmur.destroy
    redirect_to murmurs_path, notice:"つぶやきを削除しました"
  end
  
  def top
  end
  
  private
  
  def murmur_params
    params.require(:murmur).permit(:content)
  end
  
  def set_murmur
    @murmur = Murmur.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/murmurs_helper.rb
module MurmursHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_murmurs_path
    elsif action_name == 'edit'
      murmur_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tuitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/murmurs/_footer.html.erb
<footer class= footer>
  <div class="footer_wrapper">
    <P>ryohei aoki</P>
  </div>
</footer>

app/views/murmurs/_form.html.erb
<% if @murmur.errors.any? %>
  <div>
    <%# msg = @murmur.errors.full_messages %>
    <%#= msg %>
    <p>1文字以上、140文字以下でつぶやいてください</p>
  </div>
<% end %>

<%= form_with(model:@murmur, local:true, url:choose_new_or_edit)do |form| %>
  <div class=form>
    <div class=input_area>
      <%= form.label "本文" %>
      <%= form.text_area :content, placeholder: "いまどうしてる？" %> 
    </div>
    <%= form.submit "投稿", class: :submit %>
  </div>  
<% end %>

app/views/murmurs/_header.html.erb
<header class="header">
  <div class="clearfix nav_wrapper">
    <li><a href="/murmurs/top">Home</a></li>
    <li><a href="/murmurs">つぶやいたこと</a></li>
    <li><a href="/murmurs/new">もっとつぶやく</a></li>
  </div>
   
</header>

app/views/murmurs/confirm.html.erb
<html>
<body>
<div class=container>
  <%= render 'header' %>
  
  <p class=title>このつぶやきでいいですか？</p>
  
  <div class=confirm_wrapper>
  <%= form_with(model: @murmur, url: murmurs_path, local: true) do |form| %>
    <%= form.hidden_field :content %>
  
    <p class=confirm_content><%= @murmur.content %></p>
    <%= form.submit  "本当につぶやく", class: :submit %>
  <% end %>
  
  </div>
  
  <%= render 'footer' %>
</div>
</body>
</html>

app/views/murmurs/edit.html.erb
<html>
<body>
<div class=container>
  <%= render 'header' %>
  
  <p class=title>もっと良いつぶきを</p>
  
  <%= render "form" %>
  
  <%= render "footer" %>
</div>
</body>
</html>

app/views/murmurs/index.html.erb
<html>
<body>
<div class=container>
  <%= render 'header' %>
  
  <p class=title>つぶやき一覧</p>
  
  <p class=notice><%= notice %></p>
  
  <table class=index_wrapper>
    <% @murmur.each do |murmur| %>
      <div>
      <tr>
        <td class=content><%= murmur.content %></td>
      </tr>  
      <tr>
        <td><%= link_to '編集する', edit_murmur_path(murmur.id), class: "button edit" %></td>
        <td><%= link_to '削除する', murmur_path(murmur.id), class: "button delete", method: :delete, data:{confirm: "本当に削除しますか？"} %></td>
      </tr>
      </div>
    <% end %>
  </table>
  
  <%= render 'footer' %>

</div>
</body>

</html>

app/views/murmurs/new.html.erb
<html>
<body>
<div class=container>
  <%= render 'header' %>
  
  <p class=title>さあ、つぶやこう。</p>
  
  <%= render 'form' %>
  
  <%= render "footer" %>
</div>
</body>
</html>

app/views/murmurs/show.html.erb
<html>
<body>
<%= render 'header' %>

<p class=title></p>

<table>
  <tr>
    <%= @murmur.content %>
  </tr>
</table>

<%= render 'footer' %>

</body>
</html>

app/views/murmurs/top.html.erb
<html>
<body>
<div class=container>
  <%= render 'header' %>
  <div>
    <p class=title>twitter cloneのtopページ</p>
    
    <div class=top_table>
      <p class=sub_title>このアプリケーションでできること</p>
      <table>
        <tr>
          <td class=table_title>ツイート</td>
          <td class=table_content>：1〜140文字以内でつぶやけます。</td>
        </tr>
        <tr>
          <td class=table_title>ツイートの編集</td>
          <td class=table_content>：本家にはない編集機能付き<td>
        </tr>
        <tr>
          <td class=table_title>ツイートの削除</td>
          <td class=table_content>：消せます。</td>
        </tr>
      </table>
    </div>
  </div>
  <%= render "footer" %>
</div>
</body>
</html>